package cc.quark.module;

import cc.quark.Quark;
import cc.quark.module.modules.combat.*;
import cc.quark.module.modules.exploit.*;
import cc.quark.module.modules.misc.*;
import cc.quark.module.modules.movement.*;
import cc.quark.module.modules.player.*;
import cc.quark.module.modules.render.*;
import cc.quark.module.modules.world.*;
import cc.quark.module.modules.staff.*;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Central registry for all Quark modules.
 *
 * <p>Modules are instantiated in {@link #init()}, subscribed to the EventBus,
 * and can later be looked up by class or name.
 */
public class ModuleManager {

    private final List<Module> modules = new ArrayList<>();

    // -------------------------------------------------------------------------
    // Initialisation
    // -------------------------------------------------------------------------

    /**
     * Instantiate and register all modules. Call once during client init.
     */
    public void init() {

        // -------- COMBAT --------
        register(new AimAssist());
        register(new AnchorAura());
        register(new AntiAura());
        // register(new AntiBlind2());
        register(new AntiBot());
        register(new AntiFire());
        register(new AntiFireball());
        register(new AntiKnockback());
        register(new AntiPoison());
        register(new AntiSurround());
        register(new CriticalHit());
        register(new TargetStrafe());
        register(new AntiWeakness());
        register(new AttackSpeed());
        register(new AimBot());
        register(new AuraDelay());
        register(new AutoAnchor());
        register(new AutoArmor());
        register(new AutoArmorRepair());
        register(new AutoBlock());
        register(new AutoCev());
        register(new AutoClicker());
        register(new AutoCobweb());
        register(new AutoCrystal());
        register(new cc.quark.module.modules.render.ClickGuiModule());
        register(new AutoDisconnect());
        register(new AutoEgg());
        // register(new AutoLog());
        register(new AutoGapple());
        register(new AutoLeave());
        register(new AutoPearl());
        register(new AutoPot());
        // register(new AutoShield());
        register(new AutoSnowball());
        register(new AutoSoup());
        register(new cc.quark.module.modules.combat.AutoTotem());
        register(new AutoWeb());
        register(new AutoXP());
        register(new AxeOnly());
        register(new BackstabAura());
        register(new BedAura());
        register(new Berserker());
        register(new BowAimbot());
        register(new BowRelease());
        register(new Burrow());
        register(new Cleave());
        register(new ComboKeeper());
        register(new CritAura());
        register(new Criticals());
        register(new CrossbowAimbot());
        register(new CrystalAura2());
        register(new DamageTag());
        register(new Executioner());
        register(new FastBow());
        register(new FastHurt());
        register(new FireAura());
        register(new FishingAura());
        register(new ForceField());
        register(new GapAura());
        register(new HealthTags());
        register(new HitChance());
        register(new HitSelect());
        register(new HoleFiller());
        register(new cc.quark.module.modules.combat.JumpReset());
        register(new KeepSprint());
        register(new KillAura());
        register(new KnockbackBow());
        register(new LifeSteal());
        register(new MobAura());
        register(new MultiAura());
        register(new NoMissDelay());
        register(new PingSpoofCombat());
        register(new PoisonAura());
        register(new PowerHit());
        register(new PvpTimer());
        register(new QuickThrow());
        register(new RandomHit());
        register(new Reach());
        register(new Reaper());
        register(new RodAura());
        register(new SelfTrap());
        register(new ShieldBreaker());
        register(new SilentAura());
        register(new SmartAura());
        register(new SmartCrit());
        register(new Smash());
        register(new Stab());
        register(new AutoStrafe());
        register(new Surround());
        register(new SwordBlock());
        register(new TotemPop());
        register(new TridentAura());
        register(new TriggerBot());
        register(new Vampire());
        register(new Velocity());
        register(new WTap());
        register(new TotemSwap());
        register(new WTap2());
        register(new KillAura2());
        register(new AutoGapple2());
        register(new ShieldBlock());
        register(new BlastProof());
        register(new NoHitCooldown());
        register(new AntiAutoClicker());
        register(new AntiFireball2());
        register(new AutoEnderPearl());
        register(new AutoObsidian());
        register(new AutoPearl2());
        register(new CombatRecorder());
        register(new CritSpam());
        register(new HurtTimer());
        register(new ShieldSpoof());
        register(new SpeedAura());
        register(new ThornsAura());
        register(new AntiVelocity2());
        register(new ArrowDodge());
        register(new AutoShoot());
        register(new AutoSmite());
        register(new AutoTrap());
        register(new BowSpam());
        register(new CombatLog());
        register(new CrystalSwitch());
        register(new DamageIndicator());
        register(new FightBot());
        register(new QuickShield());
        register(new SilentMine());
        register(new SwordSprint());
        register(new TargetFollow());
        register(new TeamMode());
        register(new ClutchSilentAim());
        register(new BlockInSilentAim());
        register(new AntiCombatLog());
        register(new AntiHeal());
        register(new ArrowBot());
        register(new AttackRange());
        register(new AutoF3T());
        register(new AutoRespawn2());
        register(new BedAura2());
        register(new CombatHelper());
        register(new CombatRadar());
        register(new ComboKiller());
        register(new CritBot());
        register(new DragClick());
        register(new EndCrystal2());
        register(new EntityAura());
        register(new FlipFlop());
        register(new HeadshotAim());
        register(new HitboxExpander());
        register(new KillAuraPlus());
        register(new KillTracker());
        register(new PotionHelper());
        // register(new PvPTimer());
        register(new RageMode());
        register(new SurvivalKit());
        register(new TNTAura());
        register(new TargetHealth());
        register(new WeaponDelay());
        register(new WeaponSwapper());
        register(new AntiAutoClicker2());
        register(new AutoNotch());
        register(new CrystalSwitch2());
        register(new TargetStrafe2());
        register(new AutoSandCannon());
        register(new BowLead());
        register(new NecroAura());
        register(new SpeedAttack());
        register(new AntiVelocity3());
        register(new AutoWeapon());
        register(new GhostHit());
        register(new PunchAura());
        register(new TrapAura());
        register(new AntiSurround2());
        register(new CrystalCalc());
        register(new ForceAttack());
        register(new SwordBlocker());
        register(new AnchorBot());
        register(new AntiSpeedHack());
        register(new AutoBomb());
        register(new BackTrack());
        register(new BlockHit());
        register(new ExplosiveBolt());
        register(new FakeLag());
        register(new GappleAlert());
        register(new HorseKill());
        register(new PacketAttack());
        register(new PotionAura());
        register(new QuickShield2());
        register(new STap());
        register(new StepKill());
        register(new SwordFisher());
        register(new ThornsReflect());
        register(new OffhandAttack());
        register(new WTap3());
        register(new AntiArmor());
        register(new AntiCrystal());
        register(new AntiFireAura());
        register(new ArmorBreaker());
        register(new AutoCrossbow());
        register(new AutoSwitch2());
        register(new HealBlock());
        register(new StunAura());
        register(new AntiPoison2());
        register(new AutoStrike());
        register(new ExplosionAura());
        register(new FlecheThrust());
        register(new SpawnKiller());
        register(new TrapDetector());
        register(new VelocityPlus());
        register(new AntiAfk());
        register(new CritTap());
        register(new cc.quark.module.modules.combat.AntiDebuff());
        register(new CombatInfo2());
        register(new GappleCounter());
        register(new ExplosionParticles());
        register(new TotemInfo());
        register(new PvPStat());
        register(new HitConfirm());
        register(new ThrowPot());
        register(new AttackCooldown());
        register(new ComboCounter2());
        register(new CrystalPhase());
        register(new AutoMLG());
        register(new CrystalAura());
        register(new AntiFireDamage());
        register(new AutoTotem2());
        register(new Offhand());
        register(new AntiCrit2());
        register(new AutoArmor2());
        register(new BowBomb());
        register(new Criticals2());
        register(new AimAssist2());
        register(new BowAimBot());
        register(new CevBreaker());
        register(new AutoSteal());
        register(new BurstClick());
        register(new HoleSnap());
        register(new NoPush());
        register(new SurroundPlus());
        register(new AutoMace());
        register(new AutoXBow());
        register(new DragonAura());
        register(new GhastAura());
        register(new MaceAura());
        register(new SwordBlock2());

        // -------- MOVEMENT --------
        register(new Acceleration());
        register(new AirControl());
        register(new AirJump());
        register(new AirStrafe());
        register(new AirStutter());
        register(new Anchor());
        register(new AntiBounce());
        register(new AntiDrown());
        register(new AntiLevitation());
        // register(new AntiTrap());
        register(new AntiVoid());
        register(new AutoJump());
        // register(new AutoSneak());
        register(new AutoSprintToggle());
        register(new AutoWalk2());
        register(new Bhop2());
        register(new Bhop3());
        register(new Blink2());
        register(new BoatJump());
        register(new Boost());
        register(new BunnyHop());
        register(new ClimbAny());
        register(new CreativeFly());
        register(new CrouchFly());
        register(new Damage());
        register(new DiagonalSpeed());
        register(new Dolphin());
        register(new Downward());
        register(new EdgeStep());
        register(new ElytraBoost());
        register(new ElytraFly());
        register(new ElytraReplace());
        register(new ElytraSwap());
        register(new EntitySpeed());
        register(new FastClimb());
        register(new FastFall());
        register(new FastLadder());
        register(new FastSneak());
        register(new FastSwim());
        register(new Flight());
        register(new FloatHack());
        register(new Fly());
        register(new FrostWalk());
        register(new Glide());
        register(new Glitch());
        register(new GravityControl());
        register(new GravityZero());
        register(new GroundSpeed());
        register(new GroundStrafe());
        register(new BouncePad());
        register(new HighJump());
        register(new Honey());
        register(new HopStep());
        register(new Hover2());
        register(new IceSpeed());
        register(new InstantStop());
        register(new Jesus());
        register(new JetPack());
        register(new cc.quark.module.modules.movement.JumpReset());
        register(new Ladderdash());
        register(new LavaSpeed());
        register(new LavaWalk());
        register(new LedgeGrab());
        register(new LegitSpeed());
        register(new LongJump());
        register(new Momentum());
        register(new MoonWalk());
        register(new NoFall());
        register(new NoFallDamage2());
        register(new NoGravity());
        register(new NoJumpDelay());
        register(new NoPush());
        register(new NoSlime());
        register(new NoSlow());
        register(new NoSlowdown());
        register(new NoWeb());
        register(new OmniSprint());
        register(new Parkour());
        register(new Phase());
        register(new PitchFly());
        register(new QuickStop());
        register(new ReverseStep());
        register(new RubberBand());
        register(new SafeWalk());
        register(new Scaffolddash());
        register(new Skip());
        register(new Slide());
        register(new SlowFallToggle());
        register(new SmoothFly());
        register(new SnapStrafe());
        register(new SneakSpeed());
        register(new SoulSpeed());
        register(new Speed());
        register(new SpeedLimit());
        register(new SpeedToggle());
        register(new Spider());
        register(new Sprint());
        // register(new SprintReset());
        register(new Step());
        register(new Strafe());
        register(new StraightLine());
        register(new Teleport());
        register(new Tower());
        register(new Upward());
        register(new Vanilla());
        register(new VanillaFly());
        register(new Velocity2());
        register(new VelocityBoost());
        register(new WallRun());
        register(new Wallclimb());
        register(new WaterSpeed());
        register(new WaterWalk());
        register(new Webless());
        register(new YPort());
        register(new AirBrake());
        register(new AutoParkour());
        register(new BounceFly());
        register(new ClipWalk());
        register(new FastStop());
        register(new ForwardBoost());
        register(new HighStep());
        register(new KnifeSpeed());
        register(new PacketStep());
        register(new ParkourHelper());
        register(new SpeedBoost());
        register(new StepAssist());
        register(new SurfaceSwim());
        register(new WallJump());
        register(new AntiSwim());
        register(new BoatSpeed());
        register(new FastBridge());
        register(new FastElytra());
        register(new GhostMode());
        register(new HoverHeight());
        register(new LegitFly());
        register(new NoFallDamage3());
        register(new NoJumpAnimation());
        register(new NoSlowness());
        register(new RidingSpeed());
        register(new RocketBoost());
        register(new SlopeClimb());
        register(new SpringJump());
        register(new WaterJet());
        register(new AirStrafe2());
        register(new BouncePad2());
        register(new DolphinSwim());
        register(new FlyBoost());
        register(new StairJump());
        register(new AntiSlip());
        register(new AntiWater());
        register(new BunnyHop2());
        register(new CarpetFly());
        register(new CrawlFly());
        register(new DolphinDash());
        register(new ElytraBoost2());
        register(new FastDescend());
        register(new FlightBoost());
        register(new FlightSwitch());
        register(new GlideBoost());
        register(new LiquidWalk());
        register(new MomentumBoost());
        register(new PistonMotion());
        register(new SafeDescend());
        register(new SneakBoost());
        register(new SuperJump());
        register(new TrampolineJump());
        register(new VineClimb());
        register(new AntiLevitation2());
        register(new AutoSprint2());
        register(new NoFallFly());
        register(new SneakFly());
        register(new DashAbility());
        register(new HoverFly());
        register(new InertiaBoost());
        register(new PhaseWalk());
        register(new SprintJump());
        register(new TurboSprint());
        register(new AntiBoost());
        register(new FastBridge2());
        register(new HoverStep());
        register(new PortalFly());
        register(new BoatFast());
        register(new CannonJump());
        register(new SurfRide());
        register(new ZeroGrav());
        register(new AntiSink());
        register(new AutoClimb());
        register(new DoubleJump());
        register(new SwimFast());
        register(new GlideAngle());
        register(new WaterBreath());
        register(new AntiLag());
        register(new AntiWall2());
        register(new ElytraControl());
        register(new FastSwim2());
        register(new GravShift());
        register(new JetpackFly());
        register(new ParkourBoost());
        register(new SlimeBoost());
        register(new SpeedStep());
        register(new StealthWalk());
        register(new TunnelFly());
        register(new WallRide());
        register(new AntiSlowdown());
        register(new NoFog2());
        register(new AirStall());
        register(new HighJump2());
        register(new ElytraRecast());
        register(new TridentFly());
        register(new StepPlus());
        register(new SlipSpeed());
        register(new HighFly());
        register(new AntiVelocity());
        register(new InventoryWalk());
        register(new SlowFall());
        register(new AirBhop());
        register(new RocketFly());
        register(new GravityMod());
        register(new IceWalk());
        register(new ParkourAssist());
        register(new AutoFly());
        register(new CrawlMove());
        register(new NoBobbing());
        register(new SneakWalk());
        register(new EntityControl());
        register(new MountSpeed());
        register(new RideFly());

        // -------- PLAYER --------
        register(new AFKMode());
        register(new AntiAFK());
        // register(new AntiAFK2());
        register(new AntiBlind());
        register(new AntiCactus());
        register(new AntiDebuff());
        register(new AntiHungerLoss());
        register(new AntiKick());
        register(new AntiVoid2());
        register(new AutoArmorEquip());
        register(new AutoBridge());
        register(new AutoBucket());
        register(new AutoClose());
        // register(new AutoCraft());
        register(new AutoDrop());
        register(new AutoEat());
        register(new AutoFeed());
        register(new cc.quark.module.modules.combat.AntiPoison());
        register(new AutoFish());
        register(new AutoGG());
        register(new AutoHeal());
        register(new AutoHotbar());
        register(new AutoLava());
        // register(new AutoLogin());
        register(new AutoMend());
        register(new AutoMessage());
        register(new AutoMount());
        register(new AutoPotion());
        register(new AutoRegister());
        register(new AutoRepair());
        register(new AutoBot());
        register(new AutoReply());
        register(new AutoRespawn());
        register(new AutoSelect());
        register(new AutoSmelt2());
        // register(new AutoSword());
        register(new AutoSoup2());
        register(new AutoSprint());
        register(new AutoStack());
        register(new AutoSwap());
        register(new AutoSwapTool());
        register(new AutoTool());
        register(new AutoWaterBucket());
        register(new BestTool());
        register(new Blink());
        register(new BridgeAssist());
        register(new ChatBot());
        register(new cc.quark.module.modules.player.ChatFilter());
        register(new ChestAura());
        register(new cc.quark.module.modules.player.ChestStealer());
        register(new FakePlayer());
        register(new FakeSneak());
        register(new FastBreak());
        register(new FastEat());
        register(new FastInteract());
        register(new FastPlace());
        register(new FastUse2());
        register(new Freecam());
        register(new GodMode());
        register(new GuiMove());
        register(new HealthAlert());
        register(new HotbarReplenish());
        register(new InstantUse());
        register(new InventoryManager());
        register(new InventorySorter());
        register(new KeepInventory());
        register(new MiddleClickFriend());
        register(new MultiTask());
        register(new NoBreakDelay());
        register(new NoChatDelay());
        register(new NoCooldown());
        register(new NoFatigue());
        register(new NoHunger());
        register(new cc.quark.module.modules.movement.NoFall());
        register(new NoPacketKick());
        register(new NoPushItems());
        register(new NoRotate());
        register(new OpenInventory());
        register(new PacketLogger());
        register(new PacketSpammer());
        // register(new QuickDrop());
        register(new Replenish());
        register(new SaturationKeeper());
        register(new Scaffold());
        register(new ScaffoldFast());
        register(new Sneak());
        register(new SpamBot2());
        register(new ToolSaver());
        register(new TowerJump());
        register(new XCarry());
        register(new NoParticles());
        register(new InfiniteReach());
        register(new ArmorAlert());
        register(new AutoOffhand());
        register(new NoDeathScreen());
        // register(new AutoPickup());
        register(new GhostHand());
        register(new AntiGrief());
        register(new StorageOrganizer());
        register(new AutoSit());
        register(new PotionRefill());
        register(new ArmorDrop());
        register(new AutoLead());
        register(new AutoShear());
        register(new CorpseESP());
        register(new DeathLogger());
        register(new FoodAlert());
        register(new HotbarLock());
        register(new ItemSucker());
        register(new ItemTracker());
        register(new SmartEat());
        register(new AntiHunger3());
        register(new ArrowRefill());
        register(new AutoCraft2());
        register(new AutoFletch());
        register(new AutoGapple3());
        register(new AutoHealth());
        register(new AutoPotion2());
        register(new ChestFarm());
        register(new ChestRestock());
        register(new DurabilityAlert());
        register(new ExpFarm());
        register(new HandRefill());
        register(new HotbarSaver());
        register(new InvMove2());
        register(new InvSpy());
        register(new cc.quark.module.modules.player.AutoTotem());
        register(new ItemRefill());
        register(new KillOnLow());
        register(new PearlRefill());
        register(new SilentInventory());
        register(new SlotSave());
        register(new XPFarm());
        register(new AntiCurse());
        register(new AntiDropItems());
        register(new AnvilRepair());
        register(new ArmorSwapper());
        register(new AutoDropBlacklist());
        register(new AutoOffhandSwap());
        // register(new AutoMine());
        // register(new AutoSmith());
        register(new ItemDropper());
        register(new QuickEat());
        register(new SilentSwing());
        register(new AntiHunger4());
        register(new AntiWobble());
        register(new AutoBank());
        register(new AutoToss());
        register(new BlockStats());
        register(new ChestWalker());
        register(new CraftHelper());
        register(new HotbarFill());
        register(new ItemGlow());
        register(new LootSorter());
        register(new PickupDelay());
        register(new XPDisplay());
        register(new AntiItemLoss());
        register(new ChestCleaner());
        register(new GhostItems());
        register(new StairSit());
        register(new AntiEffect());
        register(new AntiExplosion());
        register(new AntiGlitch());
        register(new AutoEat2());
        register(new AutoEnchant());
        register(new AutoSwitchTool());
        register(new ClickCPS());
        register(new FoodSpam());
        register(new GappleSwitch());
        register(new ItemSorter());
        register(new NightVision2());
        register(new ShieldMode());
        register(new SwapBack());
        register(new TridentReturn());
        register(new AutoShears());
        register(new EmptyHanded());
        register(new InventoryFill());
        register(new QuickSwap());
        register(new TotemsFirst());
        register(new BuildAssist());
        register(new InventoryRefill2());
        register(new SmithingHelper());
        register(new AntiPunch());
        register(new AutoLog2());
        register(new AutoLoot());
        register(new AutoPortal());
        register(new BackPedal());
        register(new WatchDog());
        register(new AutoVault());
        register(new ChestRadar());
        register(new ItemProtect());
        register(new NoSway());
        register(new QuickCraft());
        register(new AutoEnder());
        register(new FoodTweaks());
        register(new AntiInteract());
        register(new BedESP());
        register(new ChestTracker());
        register(new MiddleClickPearl());
        register(new AntiItemDrop());
        register(new AutoSaddle());
        register(new CraftAssist());
        register(new AntiPotion2());
        register(new SmartEat());
        register(new GhostHand());
        register(new ItemSwitcher());
        register(new PearlThrower());
        register(new MountControl());
        register(new AntiHunger());
        register(new LagBack());
        register(new AutoSprint2());
        register(new NoSwing());
        register(new AntiHurtCam());
        register(new AntiAFK3());
        register(new AutoEquip());
        register(new AutoLeave());
        register(new BetterTotem());
        register(new NoInteract2());
        register(new AntiPoison3());
        register(new AutoRespawn2());
        register(new Compass2());
        register(new InvCleaner());
        register(new ShulkerPeek());
        register(new AntiBlind2());
        register(new AutoNameTag());
        register(new ChestStealer2());
        register(new EatDelay());
        register(new PickupFilter());
        register(new ThrowItems());

        // -------- RENDER --------
        register(new ActiveMods());
        register(new Ambiance());
        register(new ArmourStatus());
        register(new AnimalESP());
        register(new ArmorHUD());
        register(new AspectRatio());
        register(new BlockHighlight());
        register(new Breadcrumbs());
        register(new Chams());
        register(new ChestESP());
        register(new CombatInfo());
        register(new ChestTracers());
        register(new ClickGuiModule());
        register(new Coordinates());
        register(new Crosshair());
        register(new CrystalESP());
        register(new CustomFov());
        register(new DeathCoords());
        register(new DirectionHud());
        register(new ESP());
        register(new EntityList());
        register(new FOVChanger());
        register(new FpsDisplay());
        register(new FreeLook());
        register(new Fullbright());
        register(new GuiScale());
        register(new HealthVignette());
        register(new HUD());
        register(new Hitbox());
        register(new HoleESP());
        register(new ItemESP());
        register(new ItemPhysics());
        register(new ItemTracers());
        register(new MobESP());
        register(new ModuleList());
        register(new Nametags());
        // register(new NoBob());
        register(new NoFog());
        register(new NoHurtCam());
        register(new NotificationOverlay());
        register(new PingDisplay());
        register(new PlayerESP());
        register(new Radar());
        register(new PlayerTracers());
        register(new PotionHUD());
        register(new ServerBrand());
        register(new SessionInfo());
        register(new ShulkerViewer());
        register(new SnapLook());
        register(new SpeedDisplay());
        register(new BlockESP());
        register(new StorageESP());
        register(new TargetESP());
        register(new TargetHUD());
        register(new TNTTimer());
        register(new TimeChanger());
        register(new Trajectories());
        register(new Tracers());
        register(new TrueSight());
        register(new MotionGraph());
        register(new TabList());
        register(new ViewModel());
        register(new WeatherChanger());
        register(new VoidESP());
        register(new XRay());
        register(new Zoom());
        register(new ChunkBoundary());
        register(new MotionBlur());
        register(new CaveFinder());
        register(new Tracers2());
        // register(new NameTags());
        register(new Ambience());
        register(new ESP2());
        register(new BeaconESP());
        register(new FreeCam());
        register(new Nametag());
        register(new CompassHUD());
        register(new CustomBobbing());
        register(new GlowESP());
        register(new HitboxColor());
        register(new InventoryViewer());
        register(new PlayerInfo());
        register(new RegionBorders());
        register(new ActiveEffects());
        register(new AntiNausea());
        register(new AntiOverlay());
        register(new ArmourOverlay());
        register(new BlockHighlight2());
        register(new CustomSky());
        register(new DeathPosition());
        register(new EntityOutlines());
        register(new LightESP());
        register(new PortalOverlay());
        register(new WeaponInfo());
        register(new PingHUD());
        register(new TPSDisplay());
        register(new ArmourDurability());
        register(new ArrowCounter());
        register(new DamageNumbers());
        register(new JumpHeight());
        register(new PlayerArrows());
        register(new PotionTimer());
        register(new SpeedMeter());
        register(new BloodEffect());
        register(new BossbarMod());
        register(new HurtShake());
        register(new NametagESP());
        register(new OxygenBar());
        register(new RainbowAccent());
        register(new SaturationBar());
        register(new ShaderESP());
        register(new TotemPopHUD());
        register(new TrailEffect());
        register(new WorldBorderESP());
        register(new WorldTimeClock());
        register(new ComboCounter());
        register(new HealthIndicator());
        register(new HitColor());
        register(new ArmourESP());
        register(new ExplosionEffect());
        register(new ProjectileTracer());
        register(new ZoomPlus());
        register(new FullBright2());
        register(new RadarPlus());
        register(new MobESP2());
        register(new DistanceFog());
        register(new GlintOverride());
        register(new VehicleESP());
        register(new BlockESP2());
        register(new Noclip());
        register(new EntityFade());
        register(new ChatBox());
        register(new HotbarHighlight());
        register(new PlayerModel());
        register(new CameraClip());
        register(new MiniMap());
        register(new SignESP());
        register(new WeatherControl());
        register(new AntiBlind3());
        register(new EntityCounter());
        register(new LightESP2());
        register(new WeatherMod());
        // register(new CustomFOV());
        register(new CustomFont());
        register(new NameProtect2());
        register(new NightMode());
        register(new CrosshairPlus());
        // register(new FPSDisplay());
        register(new ArrowTracer());
        register(new ChunkBorder());
        register(new BlockOutline());
        register(new AntiAliasing());
        register(new TotemCounter());
        register(new EffectDisplay());
        register(new ItemCount());
        register(new LagMeter());
        register(new CrystalDamage());
        register(new SprintIndicator());
        register(new ArrowTrajectory());
        register(new StorageESP2());
        register(new ArmorBreakAlert());
        register(new DirectionHUD());
        register(new EntityInfo());
        register(new FovChanger());
        register(new SkyColor());
        register(new WeatherIndicator());
        register(new TunnelVision());
        register(new NametagsPlus());
        register(new BlockHighlight3());
        register(new HealthBar());
        register(new ArmorHUD2());
        register(new FPSCounter());
        register(new TimeDisplay());
        register(new PlayerList());
        register(new HotbarViewer());
        register(new TabOverlay());
        register(new DeathScreen());
        register(new EnchantInfo());
        register(new FullInventoryWarning());
        register(new HungerDisplay());
        register(new LowHealthAlert());
        register(new PotionEffectHUD());
        register(new AfkDisplay());
        register(new BreakAnimation());
        register(new ChunkBorderESP());
        register(new ClearWater());
        register(new GammaHUD());
        register(new HitMarker());
        register(new ItemGlint());
        register(new PingColor());
        register(new BlockInfo());

        // -------- WORLD --------
        register(new AutoBed());
        register(new AutoBreeder());
        register(new AutoPlace());
        register(new AutoSmelter());
        register(new AutoBridge2());
        // register(new AutoBuild());
        register(new AutoCook());
        register(new AutoDoor());
        register(new AutoFarm());
        register(new AutoFlatten());
        register(new AutoHarvest());
        register(new AutoPillar());
        register(new AutoSign());
        register(new AutoSmelt());
        register(new cc.quark.module.modules.world.ChestStealer());
        register(new ClearArea());
        register(new CropFarm());
        register(new Excavator());
        register(new FillArea());
        register(new Follow());
        register(new InstaBreak());
        register(new MelonFarm());
        register(new MiddleClick());
        register(new MineAssist());
        register(new NetherWartFarm());
        register(new Nuker());
        register(new OreAlert());
        register(new PacketMine());
        register(new PumpkinFarm());
        register(new Replant());
        register(new SpeedMine());
        register(new StashFinder());
        register(new SugarCaneFarm());
        register(new TreeFeller());
        register(new Tunneler());
        register(new VeinMiner());
        register(new AntiDrops());
        register(new TorchPlacer());
        register(new Scaffolding());
        register(new AutoFurnace());
        register(new VeinMiner2());
        register(new ChestStealer2());
        register(new SpawnProofer());
        register(new AutoWorkbench());
        register(new BlockRecorder());
        register(new AntiEnderpearl());
        register(new AutoDispenser());
        register(new AutoCompost());
        // register(new AutoFlint());
        register(new AutoMilk());
        register(new AutoNetherFarm());
        register(new AutoReplant2());
        register(new FloodPlacement());
        // register(new PathFinder());
        register(new StructureHighlight());
        register(new AutoAnvil());
        register(new AutoBrew());
        register(new AutoEnchanting());
        register(new AutoFarm2());
        register(new AutoLoom());
        register(new AutoStonecutter());
        register(new EntityCleaner());
        register(new LiquidFiller());
        register(new AntiAnvil());
        register(new AutoChop());
        register(new AutoFish2());
        register(new AutoLever());
        register(new BoneMeal2());
        register(new ChestSort());
        register(new FloodFill());
        register(new ItemAura());
        register(new MapSave());
        register(new Pathfinder());
        register(new SignRead());
        register(new TunnelBore());
        register(new AntiBlock());
        register(new AntiDragon());
        register(new AutoBee());
        register(new AutoEject());
        register(new AutoWither());
        register(new BlockSpammer());
        register(new LootFilter());
        register(new SeedAura());
        register(new VeinMine());
        register(new AutoPickupFilter());
        register(new LiquidFloodFill());
        register(new SignReader());
        register(new SwitchActivator());
        register(new SlimeFinder());
        register(new AutoLight());
        register(new AntiCreeper());
        register(new AutoBarrel());
        register(new AutoCauldron());
        register(new AutoNetherFarm2());
        register(new ChestLocker());
        register(new PearlBlocker());
        register(new PortalFinder());
        register(new TreeChop());
        register(new TreePlacer());
        register(new WorldScanner());
        register(new AutoReplenish());
        register(new BlockSwapper());
        register(new ChunkSaver());
        register(new AnimalTrap());
        register(new DungeonFinder());
        register(new AutoSplit());
        register(new BrewAssist());
        register(new CropBooster());
        register(new WitchHunt());
        register(new AntiGhast());
        register(new BlockSuction());
        register(new ExpOrb());
        register(new MobGrinder());
        register(new AntiEndermite());
        register(new AntiGhast2());
        register(new AutoComposter2());
        register(new AutoEndPortal());
        register(new CactusSpam());
        register(new EntityCleaner2());
        register(new ObsidianMiner());
        register(new PortalTeleport());
        register(new TowerBuilder());
        register(new RoofBuilder());
        register(new IceRoad());
        register(new AutoSapling());
        register(new AutoTNT());
        register(new ChunkLogger());
        register(new AutoBreaker());
        register(new LiquidPlacer());
        register(new DeepMiner());
        register(new ObsidianFarm());
        register(new AutoSmeltFarm());
        register(new DragonEggTP());
        register(new MobSpawnAlert());
        register(new CactusGrinder());
        register(new NetherHighwayHelper());
        register(new BaseBuilder());
        register(new AutoSmelter2());
        register(new StructureSave());
        register(new AutoTrader());
        register(new TreeChopper());
        register(new RapidMine());
        register(new CropCounter());
        register(new AnimalBreeder());
        register(new AutoFeed());
        register(new AutoFish3());
        register(new AutoMine2());
        register(new AutoRepair());
        register(new BlockReplace());
        register(new ChestOrganizer());
        register(new FarmHelper());
        register(new AntiSpawn());
        register(new AutoBridge3());
        register(new AutoCraft2());
        register(new AutoEnchant2());
        register(new AutoSeed());
        register(new MobStacker());

        // -------- EXPLOIT --------
        register(new AntiAim());
        register(new AntiCheat());
        register(new AntiCrash());
        register(new AntiKick2());
        register(new AntiTimeout());
        register(new AutoReconnect());
        register(new AutoWalk());
        register(new BlinkPackets());
        register(new BoatFly());
        register(new ChatSpammer());
        register(new DeSync());
        register(new Disabler());
        register(new FakePing());
        register(new FastUse());
        register(new HighwayBuilder());
        register(new LagSwitch());
        register(new LatencySpoof());
        register(new NameProtect());
        register(new NoGround());
        register(new NoPacket());
        register(new PacketCancel());
        register(new PacketFly());
        register(new PingSpoof());
        register(new HypixelBypass());
        register(new PortalGod());
        register(new Spoofer());
        register(new Timer());
        register(new ChunkLoad());
        register(new AntiHunger2());
        register(new NoRenderDistance());
        register(new AutoInteract());
        register(new PacketLogger2());
        register(new AntiSpectator());
        register(new CrashClient());
        register(new SignBypass());
        register(new AntiDesync());
        register(new AntiTablist());
        register(new BookBot());
        register(new BypassCooldown());
        register(new EntitySpammer());
        register(new LagBack());
        register(new PacketSniffer());
        register(new SpeedHack());
        register(new TabListSpoof());
        register(new TeleportExploit());
        register(new CubeCraftBypass());
        register(new MineplexBypass());
        register(new AntiTablist2());
        register(new BrandSpoof());
        register(new FlyBypass2());
        register(new NoFall2());
        register(new AntiKick3());
        register(new GhostMode2());
        register(new ImpersonateMod());
        register(new SpeedBypass2());
        register(new AntiCheatBypass());
        register(new AntiHunger2b());
        register(new AntiHunger2c());
        register(new AutoVoid());
        register(new ChestGhost());
        register(new DupeTick());
        register(new InstaPlace());
        register(new InventoryMove());
        register(new PingAbuse());
        register(new SlotAbuse());
        register(new WDL());
        register(new AntiSlow());
        register(new ClickTP());
        register(new GrimBypass());
        register(new NoCheatBypass());
        register(new TwoBTwoTBypass());
        register(new PacketManipulator());
        register(new AntiCheatAnalyzer());
        register(new Scaffold2());
        register(new EntityAbuse());
        register(new PearlPhase());
        register(new PortalGodMode());
        register(new SignEditor());
        register(new FastPlace2());
        register(new AntiTabComplete());
        register(new AntiBook());
        register(new CoordsESP());
        register(new NoGhostBlock());
        register(new AntiKnockback2());
        register(new Freecam());
        register(new Strafe());
        register(new TeleportExploit2());
        register(new AntiHunger3());
        register(new ChunkDupe());
        register(new CrashBoat());
        register(new EntitySpeed());
        register(new FastBreak2());
        register(new ItemDupe2());
        register(new PearlClip2());
        register(new AntiVoid2());
        register(new BunnyHop2());
        register(new FlyHack2());
        register(new GroundSpoof());
        register(new HighJump2());
        register(new NoSlowdown());
        register(new AntiChestLock());
        register(new BedrockBreaker());

        // -------- MISC --------
        register(new AntiDetect());
        register(new BetterChat());
        register(new Macros());
        register(new Panic());
        register(new AutoConfig());
        register(new ServerInfo());
        register(new Waypoints());
        register(new StreamerMode());
        register(new ChatLogger());
        register(new GuiTheme());
        register(new FriendList());
        register(new PopupCounter());
        register(new SendCoords());
        register(new TextReplace());
        register(new AutoCommand());
        register(new SessionStats());
        register(new ModuleHistory());
        register(new QuickMessages());
        register(new ArmourComparator());
        register(new AutoStatus());
        register(new CPSDisplay());
        register(new ChatHistory());
        register(new ClockHUD());
        register(new ConnectionInfo());
        register(new MemoryHUD());
        register(new Notifications2());
        register(new ScoreboardHUD());
        register(new TabListInfo());
        register(new cc.quark.module.modules.misc.ChatFilter());
        register(new ChatAlert());
        register(new DiscordRPC());
        register(new ModuleCounter());
        register(new SessionTimer());
        register(new AutoAccept());
        register(new AutoUpdate());
        register(new CrashLogger());
        // register(new IPLogger());
        register(new KeyLogger());
        register(new Notepad());
        register(new ScreenRecorder());
        register(new ServerHistory());
        register(new AutoResponse());
        register(new AutoAd());
        register(new GameAlert());
        register(new GlobalChat());
        register(new ChatTranslator());
        register(new AntiSpam());
        register(new NickHider());
        register(new AntiAFK2());
        register(new AutoScreenshot());
        register(new PingAlert());
        register(new AntiAFKfish());
        register(new FriendTracker());
        register(new ChatMacros());
        register(new ChatEmotes());
        register(new TabComplete());
        register(new PlayerLogger());
        register(new NoteBlockPlayer());
        register(new LightningNotifier());
        register(new ChatRepeater());
        register(new ItemRenamer());
        register(new BossBarInfo());
        register(new ClipboardShare());
        register(new Notifier());
        register(new SoundNotifier());
        register(new MapHelper());
        register(new AutoGG());
        register(new AutoSit());
        register(new ChatColors());
        register(new CoordTracker());
        register(new CustomSplash());
        register(new ItemInfo());
        register(new PanicButton());
        register(new TimeAnnouncer());
        register(new AntiChatFilter());
        register(new AutoPrivateMsg());
        register(new ChatPing());
        register(new CommandAlias());
        register(new HudEditor());
        register(new ServerAlert());
        register(new SocialSpy());
        register(new StatusMessage());
        register(new AntiFlood());

        // -------- STAFF --------
        register(new cc.quark.module.modules.staff.StaffChat());
        register(new cc.quark.module.modules.staff.Vanish());
        register(new cc.quark.module.modules.staff.Freeze());
        register(new cc.quark.module.modules.staff.InvSee());
        register(new cc.quark.module.modules.staff.BanHammer());
        register(new cc.quark.module.modules.staff.IPLogger());
        register(new cc.quark.module.modules.staff.Mute());
        register(new cc.quark.module.modules.staff.Spy());
        register(new cc.quark.module.modules.staff.ForceOp());
        register(new cc.quark.module.modules.staff.StaffESP());
        register(new cc.quark.module.modules.staff.StaffMode());
        register(new cc.quark.module.modules.staff.TeleportToPlayer());
        register(new cc.quark.module.modules.staff.PlayerInspector());
        register(new cc.quark.module.modules.staff.WatchList());
        register(new cc.quark.module.modules.staff.AntiGrief());
        register(new cc.quark.module.modules.staff.ChatMonitor());
        register(new cc.quark.module.modules.staff.GamemodeChanger());
        register(new cc.quark.module.modules.staff.SummonPlayer());
        register(new cc.quark.module.modules.staff.StaffNightVision());
        register(new cc.quark.module.modules.staff.StaffGodMode());
        register(new cc.quark.module.modules.staff.ReportHandler());
        register(new cc.quark.module.modules.staff.StaffRadar());
        register(new cc.quark.module.modules.staff.UnfreezeAll());
        register(new cc.quark.module.modules.staff.BroadcastMessage());
        register(new cc.quark.module.modules.staff.PermissionChecker());
        register(new cc.quark.module.modules.staff.ServerCrasher());
        register(new cc.quark.module.modules.staff.PlayerKicker());
        register(new cc.quark.module.modules.staff.ItemGiver());
        register(new cc.quark.module.modules.staff.TeleportHub());
        register(new cc.quark.module.modules.staff.WorldEditor());
        register(new cc.quark.module.modules.staff.NickChanger());
        register(new cc.quark.module.modules.staff.ConsoleLogger());
        register(new cc.quark.module.modules.staff.AltManager());
        register(new cc.quark.module.modules.staff.CommandSpy2());
        register(new cc.quark.module.modules.staff.MassKick());
        register(new cc.quark.module.modules.staff.PlayerAnalyzer());
        register(new cc.quark.module.modules.staff.ServerAnnounce());
        register(new cc.quark.module.modules.staff.StaffFly2());
        register(new cc.quark.module.modules.staff.WorldBackup());
        register(new cc.quark.module.modules.staff.ZoneProtect());
        register(new cc.quark.module.modules.staff.AntiDupe());
        register(new cc.quark.module.modules.staff.ChatBroadcast());
        register(new cc.quark.module.modules.staff.ClearChat());
        register(new cc.quark.module.modules.staff.FreezeAll());
        register(new cc.quark.module.modules.staff.GodCheck());
        register(new cc.quark.module.modules.staff.InvFreeze());
        register(new cc.quark.module.modules.staff.PermBan());
        register(new cc.quark.module.modules.staff.SpeedCheck());
        register(new cc.quark.module.modules.staff.StaffTP());
        register(new cc.quark.module.modules.staff.TeleportHistory());
    }

    // -------------------------------------------------------------------------
    // Registration helpers
    // -------------------------------------------------------------------------

    private void register(Module module) {
        modules.add(module);
    }

    public void unregister(Module module) {
        modules.remove(module);
        Quark.getInstance().getEventBus().unsubscribe(module);
    }

    // -------------------------------------------------------------------------
    // Tick & keybind handling
    // -------------------------------------------------------------------------

    /**
     * Called every client tick by the Fabric tick event hook in Quark.
     * Forwards the tick to every currently-enabled module that overrides onTick.
     */
    public void onTick() {
        if (Module.mc == null) {
            Module.mc = net.minecraft.client.MinecraftClient.getInstance();
        }
        for (Module module : modules) {
            if (module.isEnabled()) {
                try {
                    module.onTick();
                } catch (Exception e) {
                    Quark.LOGGER.error("Exception in module tick [{}]: {}",
                            module.getName(), e.getMessage(), e);
                }
            }
        }
    }

    /**
     * Called when a keyboard key is pressed (from MixinMinecraft via EventKey).
     * Toggles any module whose keybind matches.
     *
     * @param keyCode GLFW key code
     */
    public void onKey(int keyCode) {
        if (keyCode <= 0) return;
        if (Module.mc == null) {
            Module.mc = net.minecraft.client.MinecraftClient.getInstance();
        }
        for (Module module : modules) {
            if (module.getKeybind() == keyCode) {
                module.toggle();
            }
        }
    }

    // -------------------------------------------------------------------------
    // Lookups
    // -------------------------------------------------------------------------

    public List<Module> getModules() {
        return modules;
    }

    public List<Module> getModulesForCategory(Category category) {
        return modules.stream()
                .filter(m -> m.getCategory() == category)
                .collect(Collectors.toList());
    }

    public List<Module> getModulesByCategory(Category category) {
        return getModulesForCategory(category);
    }

    public Module getModule(String name) {
        return modules.stream()
                .filter(m -> m.getName().equalsIgnoreCase(name))
                .findFirst()
                .orElse(null);
    }

    public <T extends Module> T getModule(Class<T> clazz) {
        for (Module m : modules) {
            if (clazz.isInstance(m)) {
                return clazz.cast(m);
            }
        }
        return null;
    }

    public List<Module> getEnabledModules() {
        return modules.stream()
                .filter(Module::isEnabled)
                .sorted(Comparator.comparingInt(m -> m.getName().length()))
                .collect(Collectors.toList());
    }

    public boolean isEnabled(Class<? extends Module> clazz) {
        Module m = getModule(clazz);
        return m != null && m.isEnabled();
    }
}
